on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Install notablog
      run: npm install -g notablog
    - name: Generate HTML
      run: /usr/local/bin/notablog generate .
    - name: Publish to GitHub Pages
      run: ./publish.sh "Automated publish" public
    - name: Update CNAME
      run: echo "aideedamsyar.com" > public/CNAME

