on:
  schedule:
    - now

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: npm install
    - name: Generate HTML
      run: notablog generate .
    - name: Publish to GitHub Pages
      run: ./publish.sh "Automated publish" public
    - name: Update CNAME
      run: echo "aideedamsyar.com" > public/CNAME

